# Generated by Django 5.0.6 on 2024-06-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_assessment_assessor_alter_assessment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
