# Generated by Django 5.1.2 on 2025-03-31 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_alter_assessment_assessor_alter_student_instrument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CBT', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('practical', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('AH', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('Assignment', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mapp.student')),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='ca',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapp.ca'),
        ),
    ]
