# Generated by Django 5.1.2 on 2025-04-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0006_ca_assessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='AH',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ca',
            name='Assignment',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ca',
            name='CBT',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ca',
            name='practical',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ca',
            name='total',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=7),
        ),
    ]
