# Generated by Django 5.1.2 on 2025-06-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0009_alter_ca_ah_alter_ca_assignment_alter_ca_cbt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='AH',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ca',
            name='Assignment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ca',
            name='CBT',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ca',
            name='practical',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ca',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
