# Generated by Django 5.1.2 on 2025-07-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0010_alter_ca_ah_alter_ca_assignment_alter_ca_cbt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ca',
            old_name='AH',
            new_name='classwork',
        ),
    ]
