# Generated by Django 5.0.6 on 2026-07-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0011_rename_ah_ca_classwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedStudent',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted Student',
                'verbose_name_plural': 'Deleted Students (Recycle Bin)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mapp.student',),
        ),
        migrations.AddField(
            model_name='assessment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ca',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ca',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
