# Generated by Django 5.0.6 on 2026-07-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0012_soft_delete_recycle_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAssessment',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted Assessment',
                'verbose_name_plural': 'Deleted Assessments (Recycle Bin)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mapp.assessment',),
        ),
        migrations.CreateModel(
            name='DeletedCA',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted CA',
                'verbose_name_plural': 'Deleted CA Records (Recycle Bin)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mapp.ca',),
        ),
        migrations.CreateModel(
            name='DeletedGrade',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted Grade',
                'verbose_name_plural': 'Deleted Grades (Recycle Bin)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mapp.grade',),
        ),
    ]
